# Generated by Django 3.1.5 on 2021-01-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_city_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
    ]
