# Generated by Django 3.1.5 on 2021-01-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210116_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='posts',
        ),
        migrations.AddField(
            model_name='city',
            name='posts',
            field=models.ManyToManyField(blank=True, to='main_app.Post'),
        ),
    ]
