# Generated by Django 3.1.5 on 2021-01-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210116_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.ManyToManyField(to='main_app.City'),
        ),
    ]
