# Generated by Django 3.1.5 on 2021-01-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210116_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='posts',
        ),
    ]
