# Generated by Django 3.1.5 on 2021-01-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_city_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='posts',
            field=models.ManyToManyField(blank=True, to='main_app.Post'),
        ),
    ]
