# Generated by Django 3.1.5 on 2021-01-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_city_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='posts',
        ),
    ]
